### ISSUE TITLE
VPS subscribe (Azure) 已过期

### ISSUE THREAD

**Issue by dream-rec** [dream-rec/dream-rec.github.io#7]
### Vmess
`vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ2bWVzcyt0bHN8N1FpeC5sb3ZlQHhyYXkuY29tIiwKICAiYWRkIjogIjUyLjIyNS4yMzMuMTQxIiwKICAicG9ydCI6IDU4NDk1LAogICJpZCI6ICIzMTNjM2ZiZC1iYzA4LTQ2MjUtODM0OC1lZTc4ODczYmQ1Y2IiLAogICJhaWQiOiAwLAogICJuZXQiOiAid3MiLAogICJ0eXBlIjogIm5vbmUiLAogICJob3N0IjogIiIsCiAgInBhdGgiOiAiLzMxM2MzZmJkIiwKICAidGxzIjogIm5vbmUiCn0=`
### Vless
`vless://a8cfd5a0-10d0-4529-bcdc-cc2dd1a226a5@52.225.233.141:29232?type=ws&security=none&path=%2Fa8cfd5a0#vless+vision|Xpiw.love@xray.com`
### CF-node
**v2ray**
`vless://b183110c-5b46-4884-aa11-ec49354eab66@myvless-work.lmx450028818.workers.dev:443?encryption=none&security=tls&sni=myvless-work.lmx450028818.workers.dev&fp=randomized&type=ws&host=myvless-work.lmx450028818.workers.dev&path=%2F%3Fed%3D2048#myvless-work.lmx450028818.workers.dev`
**clash-meta**
```
- type: vless
  name: myvless-work.lmx450028818.workers.dev
  server: myvless-work.lmx450028818.workers.dev
  port: 443
  uuid: b183110c-5b46-4884-aa11-ec49354eab66
  network: ws
  tls: true
  udp: false
  sni: myvless-work.lmx450028818.workers.dev
  client-fingerprint: chrome
  ws-opts:
    path: "/?ed=2048"
    headers:
      host: myvless-work.lmx450028818.workers.dev
```

### Link
_**clash 分两种内核，一种meta原生支持vless，另外一种premium，不支持vless，且yaml语法有更改，互不兼容。
两种方式：更改内核或者下载clash verge。**_
**Clash(clash for windows默认是premium内核，只适用于meta内核)**

- 短链：http://dreammx.dpdns.org/c/czeZND1
- 长链：https://sublink-worker.lmx450028818.workers.dev/clash?config=vless%3A%2F%2Fa8cfd5a0-10d0-4529-bcdc-cc2dd1a226a5%4052.225.233.141%3A29232%3Ftype%3Dtcp%26security%3Dnone%23vless%2Bvision%7CXpiw.love%40xray.com&ua=&selectedRules=%5B%5D&customRules=%5B%5D

 **Quantumult X**

- http://lmxxx.dpdns.org/sub?target=quanx&url=vless%3A%2F%2Fa8cfd5a0-10d0-4529-bcdc-cc2dd1a226a5%4052.225.233.141%3A29232%3Ftype%3Dtcp%26security%3Dnone%23vless%2Bvision%7CXpiw.love%40xray.com&insert=false

**Quantumult**

- http://lmxxx.dpdns.org/sub?target=quan&url=vless%3A%2F%2Fa8cfd5a0-10d0-4529-bcdc-cc2dd1a226a5%4052.225.233.141%3A29232%3Ftype%3Dtcp%26security%3Dnone%23vless%2Bvision%7CXpiw.love%40xray.com&insert=false&emoji=true&list=false&tfo=false&scv=true&fdn=false&sort=false

**Shawdowrocket**

- https://dreammx.dpdns.org/c/dBppZlE
